# Generated by Django 2.1.5 on 2020-01-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_project_shuffle_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sentence_labeling',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('DocumentClassification', 'document classification'), ('SequenceLabeling', 'sequence labeling'), ('Seq2seq', 'sequence to sequence'), ('ImageClassification', 'image classification'), ('ImageCaptioning', 'image captioning'), ('ConversationClassification', 'conversation classification')], max_length=30),
        ),
    ]
