# Generated by Django 2.1.5 on 2019-09-04 23:36

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0018_project_shuffle_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioLabelingAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob', models.FloatField(blank=True, default=None, null=True)),
                ('manual', models.BooleanField(default=False)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now=True)),
                ('done', models.BooleanField(default=False)),
                ('file_name', models.TextField(blank=True)),
                ('file_path', models.TextField(blank=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_labeling_annotations', to='server.Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('DocumentClassification', 'document classification'), ('SequenceLabeling', 'sequence labeling'), ('Seq2seq', 'sequence to sequence'), ('ImageClassification', 'image classification'), ('ImageCaptioning', 'image captioning'), ('AudioLabeling', 'audio labeling (Gecko test)')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='audiolabelingannotation',
            unique_together={('document', 'user')},
        ),
    ]
