# Generated by Django 2.1.5 on 2020-03-11 04:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0019_auto_20200110_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentannotation',
            name='additional_data',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='seq2seqannotation',
            name='additional_data',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='sequenceannotation',
            name='additional_data',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('DocumentClassification', 'document classification'), ('SequenceLabelingAlt', 'sequence labeling Alt'), ('SequenceLabeling', 'sequence labeling'), ('Seq2seq', 'sequence to sequence'), ('ImageClassification', 'image classification'), ('ImageCaptioning', 'image captioning'), ('ConversationClassification', 'conversation classification')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='documentannotation',
            unique_together={('document', 'user', 'label', 'additional_data')},
        ),
    ]
