# Generated by Django 2.1.5 on 2019-11-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_auto_20191031_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolabelingannotation',
            name='data',
            field=models.TextField(blank=True),
        ),
    ]
