# Generated by Django 2.1.5 on 2020-03-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_auto_20200311_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentgoldannotation',
            name='additional_data',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='documentmlmannotation',
            name='additional_data',
            field=models.TextField(default='{}'),
        ),
    ]
