# Generated by Django 2.1.5 on 2020-06-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_auto_20191105_1553'),
        ('server', '0022_auto_20200317_0301'),
    ]

    operations = [
    ]
