# Generated by Django 2.1.5 on 2020-06-07 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0023_merge_20200604_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiolabelingannotation',
            name='additional_data',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('DocumentClassification', 'document classification'), ('SequenceLabelingAlt', 'sequence labeling Alt'), ('SequenceLabeling', 'sequence labeling'), ('Seq2seq', 'sequence to sequence'), ('ImageClassification', 'image classification'), ('ImageCaptioning', 'image captioning'), ('AudioLabeling', 'audio labeling (Gecko test)'), ('ConversationClassification', 'conversation classification')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='audiolabelingannotation',
            unique_together={('document', 'user', 'file_path')},
        ),
    ]
